//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instruction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instruction()
        {
            this.Instruction_Employees = new HashSet<Instruction_Employees>();
        }
    
        public int ID_Instruction { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> FK_InstructionEmployees { get; set; }
        public Nullable<int> FK_ViewInstruction { get; set; }
        public string Note { get; set; }
    
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Instruction_Employees> Instruction_Employees { get; set; }
        public virtual View_Instruction View_Instruction { get; set; }
    }
}
