//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization_Employees
    {
        public int ID_Organization_Employees { get; set; }
        public Nullable<int> FK_Organization { get; set; }
        public Nullable<int> FK_Employees { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
