//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Auto
    {
        public int ID_UserAuto { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public Nullable<int> FK_Employee { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
